### ISSUE TITLE
Describing a url that has a faulty og:url value fails

### ISSUE THREAD

**Issue by Dinoshauer** [hueniverse/metaphor#36]
This url (http://kb.mailchimp.com/delivery/deliverability-research/gmail-is-clipping-my-email) has the following host set for `og:url` `http//127.0.0.1/` which breaks `describe` because the `url` module cannot parse it.

Flipping the check here https://github.com/hueniverse/metaphor/blob/master/lib/index.js#L225 would fix it though.

To reproduce:

    const metaphor = require('metaphor');
    const engine = new metaphor.Engine();

    engine.describe('http://kb.mailchimp.com/delivery/deliverability-research/gmail-is-clipping-my-email', res => {
      console.log('res', res);
    });

**Comment by freeall** [comment]
At the same time, you should really consider changing the api so that it follows the standard way of asynchronous calls in javascript.

The normal way of a module like `metaphor` would be:
``` js
var metaphor = require('metaphor')
var engine = new metaphor.Engine()

engine.describe(myUrl, function (err, res) {
  if (err) ...handle the error somehow
  console.log(res)
})
```

**Comment by hueniverse** [comment]
@freeall nope. It doesn't return an error. If it fails to get a description you just get an empty one. I don't care about errors and I don't want to handle them (or explicitly ignore them).

**Comment by freeall** [comment]
@hueniverse but the problem is then that my application will then crash. Instead you should send errors to a callback.

The normal way would be something similar to:

``` js
module.exports = function (url, options, callback) {
  // when errors happen do callback(err)
  // when no errors happen do callback(null, someObject)
})
```

**Comment by hueniverse** [comment]
@freeall No need to explain to me what the callback usually looks like. I've been writing node modules for a while now. You are missing the point. You application will never crash because all errors are already handled internally. This was a bug, not an incorrect API format.

**Comment by freeall** [comment]
@hueniverse ok :) But errors from request will make the program crash. And it did. We ended up forking your module (which is super useful, by the way) just so we could handle errors.

**Comment by hueniverse** [comment]
If you are getting errors, those are bugs and you should open issues. Can you provide examples for requests that caused it to crash?
