### ISSUE TITLE
The header content contains invalid characters

### ISSUE THREAD

**Issue by malayladu** [hueniverse/metaphor#48]
I am using metaphor and trying to get the information from a website.

I am getting following error while getting data from a website.

> _http_outgoing.js:358
    > throw new TypeError('The header content contains invalid characters');
    > ^
> 
> TypeError: The header content contains invalid characters
    > at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:358:11)
    > at new ClientRequest (_http_client.js:86:14)
    > at Object.exports.request (http.js:31:10)
    > at Object.exports.request (https.js:199:15)
    > at internals.Client.request (/project/node_modules/wreck/lib/index.js:158:24)
    > at options.beforeRedirect (/project/node_modules/wreck/lib/index.js:206:38)
    > at formatCookies (/project/node_modules/metaphor/lib/index.js:104:28)
    > at cookies.forEach (/project/node_modules/metaphor/lib/index.js:118:28)
    > at Array.forEach (native)
    > at Object.beforeRedirect (/project/node_modules/metaphor/lib/index.js:113:25)
    > at ClientRequest.onResponse (/project/node_modules/wreck/lib/index.js:204:24)
    > at ClientRequest.g (events.js:291:16)
    > at emitOne (events.js:96:13)
    > at ClientRequest.emit (events.js:188:7)
    > at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    > at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)

What to do now?

**Comment by hueniverse** [comment]
What website?

**Comment by malayladu** [comment]
I tested with https://www.homeinstead.com/ 

HTH.

**Comment by hueniverse** [comment]
I cannot reproduce this. Can you still get this error?
