### ISSUE TITLE
safari 9 SyntaxError unexpected keyword 'const'. const declarations are not supported in strict mode 

### ISSUE THREAD

**Issue by matth022** [hueniverse/metaphor#51]
Hi,

First of all I would like to thank @hueniverse for this awesome package. Everything is working well in Safari 10 but when using it in Safari 9 I got the following error:

SyntaxError unexpected keyword 'const'. const declarations are not supported in strict mode.

Does somebody know how to fix this and make it work in Safari 9 ?

**Comment by hueniverse** [comment]
You need to use something like babel to convert the ES6 to supported code.
