### ISSUE TITLE
Fallback description URL does not follow redirects

### ISSUE THREAD

**Issue by antialiasis** [hueniverse/metaphor#52]
If there is no canonical URL given by a site's meta tags etc., the URL that describe() was originally called with is used in the description. However, this means that if that URL redirected somewhere, we end up with the original URL, which might be (for instance) something shortened by a URL shortener, rather than the proper URL of the page.

This wouldn't be too much of an issue except that our application tried to describe() [this website](http://www.clinicalinformaticsnews.com/2017/04/26/wearables-shaping-the-future-of-clinical-trials.aspx?utm_campaign=PostBeyond&utm_medium=Social&utm_source=Twitter&utm_term=%23135315), which has no og:url, but does have an og:image: `/template_images/ecliniqua/clinicalInformaticsNews-og.jpg`. Since this is a relative URL, our application tries to get an absolute URL, using `new URL(description.image.url, description.url)` - but because `description.url` is `http://bit.ly/2pR9IGK`, the actual link we were given, we end up generating the incorrect URL `http://bit.ly/template_images/ecliniqua/clinicalInformaticsNews-og.jpg`.

We'd actually appreciate if describe() would return absolute URLs for all images so we wouldn't have to deal with that in our application logic, but regardless, it seems obviously more correct for `description.url` (and site_name) to match the actual final destination URL than the input to the function - or else, it would be great to have some other property giving access to this information without having to fetch the URL again just to see where it redirected to.

(Looking at the rest of the describe output, the icons appear to be constructed similarly to what we're doing with the images - for this site we get `http://bit.ly/template_images/ecliniqua/favicon.ico`, which is incorrect. So that at least is definitely a bug.)

**Comment by hueniverse** [comment]
I am no longer actively using this module in my own work. However, I am happy to work on this issue as part of a paid contract.
